module.exports = Object.freeze({
  GET_GSUITE_ACTIVE_USER: "GET_GSUITE_ACTIVE_USER",
  GET_GSUITE_USER_LIST: "GET_GSUITE_USER_LIST",
  GET_GSUITE_SUPA: "GET_GSUITE_SUPA",
  CREATE_GSUITE_USER: "CREATE_GSUITE_USER",
});
